#version 430

struct BoidsForce{
	vec3 force;
};

layout(std430,binding=0) buffer destBufferBoidsForce
{
	BoidsForce boidsForce[];
} outBufferBoidsForce;

//outBufferBoidsForce.boidsForce[]

struct BoidsData {
    vec3 position;
    vec3 velocity;
    vec3 viewDir;
};

layout(std430,binding=1) buffer destBufferBoidsData
{
	BoidsData boidsData[];
} outBufferBoidsData;

//outBufferBoidsData.boidsData[]

layout(local_size_x=64,local_size_y=1,local_size_z=1) in;



uniform float _time;
uniform float _deltaTime;

#define BoundingSize vec3(100.0,100.0,100.0)

//Boids Func////////////////////////////////////////////////////////////////////////////

#define NUMTHREADS_X_NUM 64

uniform int _boids_count;
uniform float _maxBoidsDist;
//uniform float _maxBoidsField;
uniform vec3 _maxBoidsField;
uniform float _centerPosPower;
uniform float _NoiseValue;

uniform float _joinPower;
uniform float _separatePower;
uniform float _alignmentPower;

uniform float _joinDisMin;
uniform float _separateDistMin;
uniform float _alignmentDistMin;

shared BoidsData shared_BoidsData[NUMTHREADS_X_NUM];

float rand(vec2 st)
{
    return fract(sin(dot(st, vec2(12.9898, 78.233))) * 43758.5453);
}

///////////////////////////////////////////////////////////////////////////////////////

void main(){
	uint DID=gl_GlobalInvocationID.x;
	
    BoidsData boids_data=outBufferBoidsData.boidsData[DID];
    vec3 now_pos=boids_data.position;
    vec3 now_vel=boids_data.velocity;

    vec3 force=outBufferBoidsForce.boidsForce[DID].force;
    
    vec3 nex_vel=force;

    vec3 next_pos=now_pos+normalize(nex_vel)*_deltaTime*50.0;
   
    boids_data.position=next_pos;
    boids_data.velocity=nex_vel;
    boids_data.viewDir=next_pos-now_pos;

   outBufferBoidsData.boidsData[DID]=boids_data;

   outBufferBoidsForce.boidsForce[DID].force=nex_vel;
}
