#version 430

struct BoidsForce{
	vec3 force;
};

layout(std430,binding=0) buffer destBufferBoidsForce
{
	BoidsForce boidsForce[];
} outBufferBoidsForce;

struct BoidsData {
    vec3 position;
    vec3 velocity;
    vec3 viewDir;
};

layout(std430,binding=1) buffer destBufferBoidsData
{
	BoidsData boidsData[];
} outBufferBoidsData;

layout(local_size_x=256,local_size_y=1,local_size_z=1) in;

uniform float _time;
uniform float _deltaTime;
uniform float _adjustTime;

#define BoundingSize vec3(100.0,100.0,100.0)

//Boids Func////////////////////////////////////////////////////////////////////////////

#define NUMTHREADS_X_NUM 256

uniform int _boids_count;
uniform float _maxBoidsDist;
uniform float _maxBoidsField;
uniform float _centerPosPower;
uniform float _NoiseValue;

uniform float _joinPower;
uniform float _separatePower;
uniform float _alignmentPower;

uniform float _joinDisMin;
uniform float _separateDistMin;
uniform float _alignmentDistMin;

shared BoidsData shared_BoidsData[NUMTHREADS_X_NUM];

vec3 Turn(vec3 pos,vec3 vel,float uid){
    vec3 turnVel=vec3(0,0,0);
     
    //float seed=2.5;
     float seed=.85;

    if(pos.x<-1.0*_maxBoidsField){
        vel.x+=seed*abs(vel.x);
    }
     if(pos.x>_maxBoidsField){
        vel.x-=seed*abs(vel.x);
    }
    
    if(pos.y<-1.0*_maxBoidsField){
        vel.y+=seed*abs(vel.y);
    }
     if(pos.y>_maxBoidsField){
        vel.y-=seed*abs(vel.y);
    }

    if(pos.z<-1.0*_maxBoidsField){
        vel.z+=seed*abs(vel.z);
    }
     if(pos.z>_maxBoidsField){
        vel.z-=seed*abs(vel.z);
    }

    return vel;
}

float rand(vec2 st)
{
    return fract(sin(dot(st, vec2(12.9898, 78.233))) * 43758.5453);
}

///////////////////////////////////////////////////////////////////////////////////////



void main(){
	uint DID=gl_GlobalInvocationID.x;
    uint GID=gl_WorkGroupID.x;

    ////Boids Main///////////////////////
    
     BoidsData my_boids_data=outBufferBoidsData.boidsData[DID];
     vec3 my_position=my_boids_data.position;
     vec3 my_velocity=my_boids_data.velocity;

    vec3 joinVal=vec3(0,0,0);
    vec3 separateVal=vec3(0,0,0);
    vec3 alignmentVal=vec3(0,0,0);

    float joinCount=0;
    float separateCount=0;
    float alignmentCount=0;

    vec3 joinPosSum=vec3(0,0,0);
    vec3 separateVectorSum=vec3(0,0,0);
    vec3 alignmentVectorSum=vec3(0,0,0);

    vec3 joinForce=vec3(0,0,0);
    vec3 separateForce=vec3(0,0,0);
    vec3 alignmentForce=vec3(0,0,0);

    vec3 result_velocity=vec3(my_velocity);

     vec3 centerPos=vec3(0,0,0);
     float smallT=0.1;
    centerPos=vec3(cos(_time*smallT*0.001)*_centerPosPower,0.,sin(_time*smallT*0.001)*_centerPosPower);
    centerPos=vec3(0,0,_time*_centerPosPower*0.001);

    float disMin=100000000.0;
    float disMax=-10000000.0;

    float speed=0.005;
    
    for(int i=0;i<_boids_count;i+=255){
        shared_BoidsData[GID]=outBufferBoidsData.boidsData[i+GID];
        
        groupMemoryBarrier();

        for(int q=0;q<255;q++){
            vec3 other_position=shared_BoidsData[q].position;
            vec3 other_velocity=shared_BoidsData[q].velocity;

            float dis=length(other_position-my_position);
            dis=abs(dis);

           
            //join
            if(dis>0.0&&dis<=_joinDisMin){
                vec3 dirPos=other_position;
                joinPosSum+=dirPos*(1.0/dis);
                joinCount++;
            }

            //separate
            if(dis>10.0&&dis<=_separateDistMin){
                vec3 dirVector=other_position-my_position;
                separateVectorSum-=dirVector*(1.0/dis);
                separateCount++;
            }else if(dis>=0.0&&dis<=10.0){
                vec3 dirVector=other_position-my_position;
                separateVectorSum-=dirVector*1000.0;
                separateCount++;
            }

            //alignment
            if(dis>0.0&&dis<=_alignmentDistMin){
                alignmentVectorSum+=other_velocity*(1.0/dis);
                alignmentCount++;
            }

            disMin=min(disMin,dis);
            disMax=max(disMax,dis);
            
        }

         groupMemoryBarrier();

    }

     if(joinCount>0){
        //joinForce
        joinForce.x=joinPosSum.x/float(joinCount);
        joinForce.y=joinPosSum.y/float(joinCount);
        joinForce.z=joinPosSum.z/float(joinCount);
        joinForce=joinForce-my_position;
        joinForce=normalize(joinForce)*speed;
        
        result_velocity+=vec3(joinForce*_joinPower);
        
       
    }

     if(separateCount>0){
        //separateForce
        separateForce.x=separateVectorSum.x/float(separateVectorSum);
        separateForce.y=separateVectorSum.y/float(separateVectorSum);
        separateForce.z=separateVectorSum.z/float(separateVectorSum);
        separateForce=separateForce-my_position;
        separateForce=normalize(separateForce)*speed;

      
        result_velocity+=vec3(separateForce*_separatePower);
        
        
    }

     if(alignmentCount>0){
        //alignmentForce
        alignmentForce.x=alignmentVectorSum.x/float(alignmentCount);
        alignmentForce.y=alignmentVectorSum.y/float(alignmentCount);
        alignmentForce.z=alignmentVectorSum.z/float(alignmentCount);
        alignmentForce=alignmentForce-my_position;
        alignmentForce=normalize(alignmentForce)*speed;

        result_velocity+=vec3(alignmentForce*_alignmentPower);
    
    }
   
    result_velocity=Turn(my_position,result_velocity,float(DID));

    outBufferBoidsForce.boidsForce[DID].force=vec3(
        (isnan(result_velocity.x))?0.005:result_velocity.x,
        (isnan(result_velocity.y))?0.005:result_velocity.y,
        (isnan(result_velocity.z))?0.005:result_velocity.z
    );

}
