#version 430

//BoidsData/////
struct BoidsData {
    vec3 position;
    vec3 velocity;
    vec3 viewDir;
};

layout(std430,binding=1) buffer destBufferBoidsData
{
	BoidsData boidsData[];
} outBufferBoidsData;

//input/////
 struct input_data{
    vec3 nextInputPosition;
};

// outBufferBoidsData.boidsData[].position

layout(std430,binding=2) buffer destBuffer_input_data
{
	input_data iData[];
} outBuffer_input_data;

// outBuffer_input_data.iData[].nextInputPosition

//node/////
struct node{
    vec3 node_position;
    float node_life;
    int renderFlag;
};

layout(std430,binding=3) buffer destBuffer_node
{
	node nodes[];
} outBuffer_node;

// outBuffer_node.nodes[].node_position

//trail///////
struct trail{
    int nextCalNodeIndex;
    int leftSideFirst;
    int rightSideFirst;
    int rightSideSecond;
    vec4 trail_color;
};

layout(std430,binding=4) buffer destBuffer_trail
{
	trail trails[];
} outBuffer_trail;

// outBuffer_trail.trails[].nextCalNodeIndex

//thread
layout(local_size_x=256,local_size_y=1,local_size_z=1) in;

////////////////////////////////////////////////////////////////////////////

//uniform

uniform int _nodeSegment;
uniform float _nodeDistanceMin;
uniform float _time;
uniform float _initNodeLife;

//////

//outBufferBoidsData.boidsData
// outBuffer_input_data.iData
//outBuffer_node.nodes
//outBuffer_trail.trails

void main(){
	uint DID=gl_GlobalInvocationID.x;
	
	int trailIndex=int(DID);
    trail trail_data=outBuffer_trail.trails[trailIndex];
    input_data input_next_data=outBuffer_input_data.iData[trailIndex];
    int nowCalNodeIndex=trail_data.nextCalNodeIndex;
    int myNodeIndex=trailIndex*_nodeSegment+nowCalNodeIndex;
    node node_data=outBuffer_node.nodes[myNodeIndex];
    
    float calNodeLength=length(input_next_data.nextInputPosition-node_data.node_position);

    if(calNodeLength>=_nodeDistanceMin){
       //cal node
        node_data.renderFlag++;
        node_data.node_position=input_next_data.nextInputPosition;
        node_data.node_life=_time*0.001;
        //cal trail
        int leftSideFirst=nowCalNodeIndex;
        int rightSideFirst=(nowCalNodeIndex+(_nodeSegment-1))%_nodeSegment;
        int rightSideSecond=(nowCalNodeIndex+(_nodeSegment-2))%_nodeSegment;

        nowCalNodeIndex++;
        nowCalNodeIndex=int(nowCalNodeIndex%_nodeSegment);
        trail_data.nextCalNodeIndex=nowCalNodeIndex;
        trail_data.leftSideFirst=leftSideFirst;
        trail_data.rightSideFirst=rightSideFirst;
        trail_data.rightSideSecond=rightSideSecond;

        //write to buffer
        outBuffer_node.nodes[myNodeIndex]=node_data;
        outBuffer_trail.trails[trailIndex]=trail_data;
    } 
}
